### ISSUE TITLE
Is it possible to get a >7:1 contrast ratio on buttons?

### ISSUE THREAD

**Issue by isaac-8601** [material-foundation/material-color-utilities#104]
It's possible that there's just an error on the Material site, but I wanted to check just in case there is something bigger going on.

On the [Accessibility page](https://m3.material.io/styles/color/the-color-system/accessibility) for the color system, there's an image that indicates a contrast ratio of 7.72:1, which is quite high! The _Contrast in Material_ section below it mentions that for tonal differences of 70 steps, the colors achieve at least a 7:1 ratio. 

However, when we downloaded the image and checked manually, we got a contrast ratio of 6.46:1 using a background of #386A20 and a foreground of #ffffff. Which is also quite good! But not what the image indicates. I assume that there's a margin of error since we're looking at a lossy image, but since the color token for a light-themed button's background is typically primary40, it doesn't seem likely that the ratio is correct. (Of course, the documentation says "at least" but the image is the more important bit here.)

<img width="328" alt="unnamed" src="https://github.com/material-foundation/material-color-utilities/assets/106764128/4c108534-ed6f-41aa-9303-068a77c25cd9">  

_The image in question from the Material documentation._

Is it possible the image is incorrect, or is there something else we might be missing?

**Comment by Nevro** [comment]
Yes, this image represents the wrong contrast between colors! You can adjust desired scheme contrast level with new dynamic schemes..

```javascript
import { Hct, SchemeTonalSpot, MaterialDynamicColors, xyzFromArgb, hexFromArgb, Contrast } from "@material/material-color-utilities";

const sourceColorHct = Hct.from(138, 48, 36);
const isDarkScheme = false;
const schemeContrastLevel = 0.35; //between -1.0 and 1.0

const scheme = new SchemeTonalSpot(sourceColorHct, isDarkScheme, schemeContrastLevel);

const primaryArgb = MaterialDynamicColors.primary.getArgb(scheme);
const onPrimaryArgb = MaterialDynamicColors.onPrimary.getArgb(scheme);

console.log({
  primary: hexFromArgb(primaryArgb),
  onPrimary: hexFromArgb(onPrimaryArgb),
  contrast: Contrast.ratioOfYs(xyzFromArgb(primaryArgb)[1], xyzFromArgb(onPrimaryArgb)[1])	
});
```

```
{
  primary: '#2f501d',
  onPrimary: '#c5eeaa',
  contrast: 7.079533262310701
}
```
