### ISSUE TITLE
Wrong chroma for neutral colors

### ISSUE THREAD

**Issue by MrEbbinghaus** [material-foundation/material-color-utilities#114]
The blog post [Introducing Tone-based Surfaces in Material 3](https://material.io/blog/tone-based-surface-color-m3) from March states:

> The chroma for the neutral palette is increased from 4 to 6

This isn't reflected in any of the applications.

Is there a document where these values are noted? A single source of truth?
https://m3.material.io/styles/color/the-color-system doesn't mention any chroma values. 

-----

https://github.com/material-foundation/material-color-utilities/blob/12b75a01476c41bb2ba9c585cfc71f1a7692aa11/typescript/palettes/core_palette.ts#L111

https://github.com/material-foundation/material-color-utilities/blob/12b75a01476c41bb2ba9c585cfc71f1a7692aa11/swift/Sources/MaterialColorUtilities/Palettes/CorePalette.swift#L70

https://github.com/material-foundation/material-color-utilities/blob/12b75a01476c41bb2ba9c585cfc71f1a7692aa11/java/palettes/CorePalette.java#L62

https://github.com/material-foundation/material-color-utilities/blob/12b75a01476c41bb2ba9c585cfc71f1a7692aa11/cpp/palettes/core.cc#L41

https://github.com/material-foundation/material-color-utilities/blob/12b75a01476c41bb2ba9c585cfc71f1a7692aa11/dart/lib/palettes/core_palette.dart#L57

**Comment by MrEbbinghaus** [comment]
Just noticed that the other remarks from the blogpost aren't reflected either. Do you want new issues for this or should I update this one?

> The default light theme surface role from tone 99 to tone 98

https://github.com/material-foundation/material-color-utilities/blob/12b75a01476c41bb2ba9c585cfc71f1a7692aa11/typescript/scheme/scheme.ts#L197

> Surface roles in dark theme are slightly darkened

![image](https://github.com/material-foundation/material-color-utilities/assets/2965273/ca256389-cec2-4446-90fd-c287e8eb2cdb)


https://github.com/material-foundation/material-color-utilities/blob/12b75a01476c41bb2ba9c585cfc71f1a7692aa11/typescript/scheme/scheme.ts#L234

**Comment by guidezpl** [comment]
cc @pennzht

**Comment by MrEbbinghaus** [comment]
So, the Dart implementation is considered the reference? 

Nevertheless, it would be great to have a single spec instead of reference implementations.

This would allow designers and devs to use/implement material color themselves, without needing to work through the code to understand what colors are generated in which way.
