### ISSUE TITLE
`DynamicScheme` is impossible to construct in TypeScript

### ISSUE THREAD

**Issue by JoshuaBrest** [material-foundation/material-color-utilities#151]
In the current TypeScript implementation, it is impossible to construct a `DynamicScheme`. The constructor for `DynamicScheme` requires the `Variant` enum, which is not a const enum. This enum is not exported. Additionally, no functionality is available to auto-generate a DynamicScheme from a given color or image, which limits dynamic usability.

## Fix

File: typescript/index.ts
```diff
  export * from './dynamiccolor/dynamic_color.js';
  export * from './dynamiccolor/dynamic_scheme.js';
  export * from './dynamiccolor/material_dynamic_colors.js';
+ export * from './dynamiccolor/variant.js';
```

**Comment by anh2111htdd** [comment]
I've exported variant as you suggested. To construct a DynamicScheme in most case, you can use one of the constructors in https://github.com/material-foundation/material-color-utilities/tree/main/typescript/scheme.
