### ISSUE TITLE
Dart : Wrong Color Generation

### ISSUE THREAD

**Issue by Hacker437** [material-foundation/material-color-utilities#16]
The Primary Container generated by this package is Different from the color generated from Website

**Comment by guidezpl** [comment]
Can you please provide more details? Will help me investigate :)

**Comment by Hacker437** [comment]
> Can you please provide more details? Will help me investigate :)

Sure, I am busy now so I will give details tomorrow.

**Comment by Hacker437** [comment]
Well...

Here is the screenshot of FAB android using the colors generated by web

![Using primary container generated by web](https://user-images.githubusercontent.com/68219142/145052039-35e1ad83-e0cd-41ad-a00a-2fdf1b2a6d83.jpg)

Now I tries to use material 3 color scheme by using this library. If I provide the same color used to generate on web and apply primary container on flutter I get the following result

![Using Primary container from core pallete of this library](https://user-images.githubusercontent.com/68219142/145052403-24bdab5c-98d0-4765-a98f-c629f1e0c79d.jpg).


After deeply studying the docs at material website I found that It may be a problem of web but I can't give surety as I don't have an android 12 device

**Comment by guidezpl** [comment]
What is the provided color?

**Comment by Hacker437** [comment]
#9C4247

**Comment by guidezpl** [comment]
Thanks, I've filed an internal issue b/210455181 and will close this one

**Comment by Hacker437** [comment]
> Thanks, I've filed an internal issue b/210455181 to update the theme builder and will close this one

Thanks

**Comment by Hacker437** [comment]
> 210455181

@guidezpl How do I follow up with this issue

**Comment by guidezpl** [comment]
It's internal-only, unfortunately. But this here issue is linked there so once it's resolved myself of someone else will comment here

**Comment by guidezpl** [comment]
Fixed upstream

**Comment by Hacker437** [comment]
Thank you
