### ISSUE TITLE
Question about Scheme and/or ColorPalette behavior

### ISSUE THREAD

**Issue by zeshuaro** [material-foundation/material-color-utilities#22]
Consider the following code:

```dart
import 'package:flutter/material.dart';
import 'package:material_color_utilities/material_color_utilities.dart';

void main() {
  const color = Colors.blue;
  final scheme = Scheme.light(color.value);
}
```

Should `color.value` be equal to `scheme.primary`? Right now these two values are different. 

I can see that `Scheme.light` calls `CorePalette.of(color)` and then assign `corePalette.primary.get(40)` as the primary color. Maybe another question would be should `corePalette.primary.get(40)` be equal to the color that was provided initially? 

I was also reading the [color system](https://m3.material.io/styles/color/the-color-system/key-colors-tones) page, and seems like the primary color should have a tone of 40. So I'm just wondering what's the expected behavior when using `Scheme.light` and/or `CorePlatte.of`?

**Comment by guidezpl** [comment]
> Should color.value be equal to scheme.primary? Right now these two values are different.

I believe so, but only if your input color is of tone 40, for a light scheme. In this case `Colors.blue` is `Colors.blue.shade500` which has a tone of 50.

> This is by design and guarantees the accessibility of the system, e.g. that the `onPrimary` color will be fully legible, no matter the color.

The side effect is that most of the time, your input color isn't found exactly in the output scheme.

**Comment by zeshuaro** [comment]
I see thanks for the clarification!
