### ISSUE TITLE
[typescript] package.json `type` should be `module`

### ISSUE THREAD

**Issue by michaelurban** [material-foundation/material-color-utilities#29]
The package is distributed as ESM, not CommonJS.

Pull request here: https://github.com/material-foundation/material-color-utilities/pull/28

**Comment by michaelurban** [comment]
Closed in: https://github.com/material-foundation/material-color-utilities/commit/d3ba3125268c4006da8cea4922b793c8287b2167

**Comment by willster277** [comment]
When is this expected to be released?
Currently v0.1.2 is not available, which effectively renders this library unusable.
