### ISSUE TITLE
Update the value of the Dart package's `repository` field

### ISSUE THREAD

**Issue by devoncarew** [material-foundation/material-color-utilities#41]
Hi, I see this is a read-only mirror (so I'm opening an issue instead of a PR). It would be useful to update the value the the Dart package's `repository` field to include information about the package's path within the repo - as well as the repo's url itself. This helps tooling know where to find the dart code, now which commits actually affect the dart package, ...

Here's what the field should look like:

```
repository: https://github.com/material-foundation/material-color-utilities/tree/main/dart
```

Thanks!

**Comment by guidezpl** [comment]
Will be fixed shortly, cl/451320120
