### ISSUE TITLE
Is it possible to use the quantizer in a project licensed under GPL-2.0

### ISSUE THREAD

**Issue by easyteacher** [material-foundation/material-color-utilities#53]
As GPL-2.0 is incompatible with Apache-2.0 License, I would like to know if there is a way to use the quantizer if the license can't be changed?

Thanks in advance.

**Comment by guidezpl** [comment]
I hope https://opensource.stackexchange.com/questions/1357/can-i-link-a-apache-2-0-library-into-software-under-gplv2 answers your question
