### ISSUE TITLE
Broken TonalPalette equality operator in dart

### ISSUE THREAD

**Issue by KalilDev** [material-foundation/material-color-utilities#56]
In TonalPalette, when one of the palettes was not generated using the _fromHueAndChroma operator, the following code is called:https://github.com/material-foundation/material-color-utilities/blob/dfc3fae69e77b788eaf159f84fe7fc98aa3c4b8d/dart/lib/palettes/tonal_palette.dart#L113 . The issue is that when one of the palettes's cache was not filled, the comparision results in a empty set contains an empty set, for example. This results in operator== resulting in true, always, even when the palettes are different. An testcase for this it https://github.com/kalildev/material_color_utilities_issue .

**Comment by guidezpl** [comment]
Thanks for filing an issue and for the test case, I'll get a fix out shortly.
