### ISSUE TITLE
Easy access to material Design colors

### ISSUE THREAD

**Issue by guyluz11** [material-foundation/material-color-utilities#63]
There is no package for dart native to get material colors.

In Flutter you can get colors like this `Colors.orange` using the Flutter package [material](https://pub.dev/packages/material).

![image](https://user-images.githubusercontent.com/9304740/195992647-645eca39-dd2d-48ea-b5e6-17233f9be0e6.png)

Can we add a way to use the colors?.

We can use `Colors.orange` like in the packge or change it so that it will not collide inside Flutter projects.

**Comment by guidezpl** [comment]
Thanks for filing, we don't have plans to make these Material 1 and 2 colors available since Material 3 is the current version. Therefore, closing this issue.

**Comment by guyluz11** [comment]
Just to make sure I understand.
Using this package I can't pick a single color from Material 3 (similar to using Colors.orange) since Material 3 always generates color from something like image.

**Comment by guidezpl** [comment]
So that's the thing, Material 3 doesn't provide a set of colors. So it's up to you to create a list of your desired color options.

**Comment by guyluz11** [comment]
Ok thanks 👍
