### ISSUE TITLE
Getting the color tone value in a palette

### ISSUE THREAD

**Issue by mystrdat** [material-foundation/material-color-utilities#67]
My usecase is generating relative tones. Right now, I have to loop through TonalPalette results with floating point precision to get the nearest tone value of my input color. Would it be possible to add a helper fn that returns the tone value of input color in the palette that TonalPalette creates?

**Comment by kirill-grouchnikov** [comment]
I don't think there's any guarantee that the seed color appears in the generated palette

**Comment by mystrdat** [comment]
From my limited testing it seemed to have always appeared as a tone, most often as a fraction of tone integer. Are you certain?

**Comment by kirill-grouchnikov** [comment]
What do you mean as a fraction? You will certainly get one of the colors that is close to the seed, but it won't be the exact match, probably

**Comment by albi005** [comment]
I think you are looking for the Hct class:
```ts
let hct = Hct.fromInt(color);
let tone = hct.tone;
```

**Comment by mystrdat** [comment]
> I think you are looking for the Hct class:
> 
> ```ts
> let hct = Hct.fromInt(color);
> let tone = hct.tone;
> ```

Amazing that's it, thank you very much!
