### ISSUE TITLE
Use with latest Node.JS does NOT work because imports and exports do not follow ES6 modules rules, need file extension on import path.

### ISSUE THREAD

**Issue by edgarlcs** [material-foundation/material-color-utilities#68]
Hello I tried to use this module with Next.JS and it was returning the 'ERR_MODULE_NOT_FOUND' when trying to use it. To fix the issue I added the ".js" extension to all the exports and imports on all files.

**Comment by willster277** [comment]
The library is completely unusable.
This has been known for 7 months #35 
I've submitted a PR which fixes this #61

**Comment by AllanPinheiroDeLima** [comment]
> The library is completely unusable. This has been known for 7 months #35 I've submitted a PR which fixes this #61

Can't we fork this lib and apply this correction ? In JS it is pretty hard to make it work correctly as of now

**Comment by WillsterJohnson** [comment]
@AllanPinheiroDeLima sure, the fork is mentioned in this comment https://github.com/material-foundation/material-color-utilities/issues/35#issuecomment-1214133323

**Comment by guidezpl** [comment]
This will be fixed in the next release, closing
