### ISSUE TITLE
Is it possible to fix(preserve) Primary color without changing ?

### ISSUE THREAD

**Issue by kohheepeace** [material-foundation/material-color-utilities#77]
## Question
Is it possible to fix the PRIMARY color without changing it?

## Usecase

Consider a company that already has a brand color and wants to use it as a primary color.

## Problem
The input and output of the PRIMARY color is significantly different as shown in the example below.

### Twitter (brand color: #1DA1F2)
| Input(#1DA1F2) | Output(#006399) |
| --- | --- |
| ![Screenshot 2023-02-16 at 14 49 41](https://user-images.githubusercontent.com/29557494/219289584-f68d3c68-9e0a-43ed-ba0f-d2ff1154a558.png)| ![Screenshot 2023-02-16 at 14 50 03](https://user-images.githubusercontent.com/29557494/219289645-314e8671-a69b-4434-817d-48a90ee0a665.png)|

### Airbnb (brand color: #FF5A5F)
| Input(#FF5A5F) | Output(#b52330) |
| --- | --- |
| ![Screenshot 2023-02-16 at 14 48 04](https://user-images.githubusercontent.com/29557494/219289323-f85c5fca-b2c1-4ebd-815f-441cdceaf3eb.png)| ![Screenshot 2023-02-16 at 14 47 30](https://user-images.githubusercontent.com/29557494/219289207-4537a9d1-17aa-4506-93d1-a1afdb7eae06.png) |

**Comment by kohheepeace** [comment]
Oops, I just noticed this issue https://github.com/material-foundation/material-color-utilities/issues/75 is mentioning similar requests.

**Comment by guidezpl** [comment]
That is the purpose of the fidelity scheme

**Comment by kohheepeace** [comment]
Thanks ! 

At first I thought I could just replace the primary color with the source color, but then I realized that `text-primary` rarely works for yellow brand colors, ex: mailchimp.

So I am 100% in favor of the idea of making `primary-container` the `source-color`. Because it is a "container".

I hope it gets implemented in Typescript too 👍

**Comment by guidezpl** [comment]
Exactly. It's currently in review for TS!

**Comment by pk111and222** [comment]
> Exactly. It's currently in review for TS!


Ok, now how can I use this pattern in ts? At least for now, the themeFromSourceColor method provided by the example can't achieve this effect.

**Comment by maiconcarraro** [comment]
@pk111and222 
> Ok, now how can I use this pattern in ts? At least for now, the themeFromSourceColor method provided by the example can't achieve this effect.

Seems like you need to use the specific dynamic schemes here: https://github.com/material-foundation/material-color-utilities/tree/main/typescript/scheme + plus https://github.com/material-foundation/material-color-utilities/blob/main/make_schemes.md#step-2--obtaining-colors

I didn't find a way to use `themeFromSourceColor` w/ variants. (was looking for the same), to preserve primary color is recommend to use Fidelity: https://github.com/material-foundation/material-color-utilities/blob/main/typescript/scheme/scheme_fidelity.ts

**Comment by pk111and222** [comment]
> @pk111and222
> 
> > Ok, now how can I use this pattern in ts? At least for now, the themeFromSourceColor method provided by the example can't achieve this effect.
> 
> Seems like you need to use the specific dynamic schemes here: https://github.com/material-foundation/material-color-utilities/tree/main/typescript/scheme + plus https://github.com/material-foundation/material-color-utilities/blob/main/make_schemes.md#step-2--obtaining-colors
> 
> I didn't find a way to use `themeFromSourceColor` w/ variants. (was looking for the same), to preserve primary color is recommended to use Fidelity: https://github.com/material-foundation/material-color-utilities/blob/main/typescript/scheme/scheme_fidelity.ts

This sounds a bit complicated and confusing, especially for developers who want to get a set of standard colors by not knowing the details. I feel that this library doesn't follow up the change of later ideas well.

**Comment by pk111and222** [comment]
@maiconcarraro 
> > This sounds a bit complicated and confusing, especially for developers who want to get a set of standard colors by not knowing the details. I feel that this library doesn't follow up the change of later ideas well.
> 
> yep, I created a react hook for my project and published in case anyone is looking for this abstraction https://www.npmjs.com/package/use-material-you

This sounds so cool, but unfortunately when I was looking for this library, I was going to create a UI library for SolidJS. Can I get inspiration directly from your library? Or make some of your core methods into a general function instead of not just the react hook?

**Comment by maiconcarraro** [comment]
@pk111and222 
> This sounds so cool, but unfortunately when I was looking for this library, I was going to create a UI library for SolidJS. Can I get inspiration directly from your library? Or make some of your core methods into a general function instead of not just the react hook?

I'm cool either way, you can also send a PR to the project if you want, then I can release a new version, otherwise I'll extract the functions later this week 👍

**Comment by pk111and222** [comment]
@maiconcarraro 
> I'm cool either way, you can also send a PR to the project if you want, then I can release a new version, otherwise I'll extract the functions later this week 👍

I'm sorry, I don't think I'm a high-level developer. In order not to affect the cleanliness and high level of your code base, I decided to open a code base myself to deal with the related functions of solid quickly, so I need to copy the code of the color generation part in your code. Thank you.
attach my link, https://github.com/pk111and222/solid-material-color。We can make progress together
