### ISSUE TITLE
Typescript utils won't install with the new version ( 0.2.1 )

### ISSUE THREAD

**Issue by glued** [material-foundation/material-color-utilities#79]
The new version that was just published throws a bunch of errors when trying to install with `npm i` 
```
npm ERR! command failed
npm ERR! command sh -c npm run build
npm ERR! > @material/material-color-utilities@0.2.1 build
npm ERR! > npm run remove-build && tsc
npm ERR! 
npm ERR! 
npm ERR! > @material/material-color-utilities@0.2.1 remove-build
npm ERR! > rm -rf dist
npm ERR! 
npm ERR! blend/blend_test.ts(24,1): error TS2304: Cannot find name 'beforeEach'.
npm ERR! blend/blend_test.ts(25,3): error TS2708: Cannot use namespace 'jasmine' as a value.
npm ERR! blend/blend_test.ts(33,1): error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! blend/blend_test.ts(34,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! blend/blend_test.ts(36,5): error TS2304: Cannot find name 'expect'.
npm ERR! blend/blend_test.ts(39,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! blend/blend_test.ts(41,5): error TS2304: Cannot find name 'expect'.
...
```

**Comment by glued** [comment]
tsconfig is including tests in the build

**Comment by guidezpl** [comment]
@rodydavis could you please take a look?

**Comment by grzegorzCieslik95** [comment]
The same problem - 
![image](https://user-images.githubusercontent.com/22835944/220431897-27a03557-9380-4ca2-85c8-4ab5d229a52d.png)
![image](https://user-images.githubusercontent.com/22835944/220431924-77dffff4-5e59-4b2c-b69f-c22dcef6aba3.png)

**Comment by NDoolan360** [comment]
Ran into the same error,
Looks like it's in the postinstall scripts.

```
154 info run @material/material-color-utilities@0.2.1 postinstall node_modules/@material/material-color-utilities npm run build
155 info run @material/material-color-utilities@0.2.1 postinstall { code: 1, signal: null }
...
163 verbose node v18.12.0
164 verbose npm  v8.19.2
165 error code 1
166 error path C:\Users\me\project\node_modules\@material\material-color-utilities
167 error command failed
168 error command C:\WINDOWS\system32\cmd.exe /d /s /c npm run build
169 error > @material/material-color-utilities@0.2.1 build
169 error > npm run remove-build && tsc
169 error
169 error
169 error > @material/material-color-utilities@0.2.1 remove-build
169 error > rm -rf dist
170 error 'rm' is not recognized as an internal or external command,
170 error operable program or batch file.
171 verbose exit 1
```

You can run the install without these using:
`npm i @material/material-color-utilities --ignore-scripts`

Not sure what the implications of not running these scripts is tho. 🤷‍♂️

**Comment by rodydavis** [comment]
Is is meant to run on bash on Linux or macOS.

related issue: https://github.com/akosbalasko/yarle/issues/220

**Comment by Mordech** [comment]
The `postinstall` script makes `prepublishOnly` redundant. And `tsconfig.json` should exclude `**/*_test.ts` to not rely on ts files with dev dependencies.

**Comment by WillsterJohnson** [comment]
It took approximately 3 seconds of looking at the package.json to know exactly how to resolve the installation fail.

That means none of Google's team have looked at this for longer than a fraction of a second. Either that or Google's devs were unable to resolve this blindingly simple config issue.

**Comment by rodydavis** [comment]
Fixing the change internally and will push out, also working on fixing some other related issues.

**Comment by jiblett1000** [comment]
@rodydavis Seems to be working in 2.2 so far (at least build-wise). Tinkering with it at the moment.

**Comment by guidezpl** [comment]
@WillsterJohnson That is not an acceptable way to speak to any developer, please refer to https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette and consider making more constructive comments in the future.
