### ISSUE TITLE
Problems fixed in internal response to #61 have returned/were not entirely resolved

### ISSUE THREAD

**Issue by WillsterJohnson** [material-foundation/material-color-utilities#82]
Ref: https://github.com/material-foundation/material-color-utilities/pull/61

It seems like this may be partially my fault as I hadn't noticed some imports are introducing files into the global scope via `import "file"`, a practice I don't find myself doing other than for test runners.

I noticed this when importing a function from [`quantize/lab_point_provider`](https://github.com/material-foundation/material-color-utilities/blob/bde4d30cad3cb766c45bcd8187da74ac56a3e292/typescript/quantize/lab_point_provider.ts#L18), in the dist code it includes
```js
import './point_provider';
```
and sure enough it's the same in the source.

In any case, the library remains impossible to execute, except for on node with experimental flags (browsers will not run this, and browsers are the primary target for frontend JS).

I'll dig through and find files/line numbers of all occurences. The reason I say this may be my fault is because the git blame for the file mentioned dates back before I raised #61, although in that PR this particular instance **is** fixed ([see comment I added to the PR before posting this issue](https://github.com/material-foundation/material-color-utilities/pull/61/files#r1123346459)).
If you used my JS replacer script (though I suspect for good practice & security that you didn't) then the result should have been identical to the PR I submitted - maybe the replacer that was used neglects this type of import?

**Severity:** I cannot use this library without a fix

(edit; spelling)

**Comment by WillsterJohnson** [comment]
The import statement mentioned is the only one which should have a `.js` but doesn't. Seems like an edge case of whichever replacer was used.

**Comment by pennzht** [comment]
Fixing now.

**Comment by rodydavis** [comment]
Approved change, and should be out soon!

**Comment by WillsterJohnson** [comment]
sweet, thanks folks!

**Comment by WillsterJohnson** [comment]
0.2.3 fixes this
