### ISSUE TITLE
Typescript theme custom colors return type

### ISSUE THREAD

**Issue by jiblett1000** [material-foundation/material-color-utilities#86]
Hello,

I'm using the theme and I am adding a couple custom colors. I was just thinking it might be more ideal to return the colors as an object, using the the provided `name` key instead of as an object array. Then the color could just be accessed as such `theme.customColors.colorName`. I can just use find or findIndex to get the correct color, but just a thought.

Thanks for the great utilities!
-Cheers

**Comment by rodydavis** [comment]
yeah that was the original api, but we use this library on the [theme builder](https://m3.material.io/theme-builder) and one of the things we ran into is having multiple colors with the same name (though not recommended) and easy way to rename a color (by index).

**Comment by jiblett1000** [comment]
@rodydavis Ah ok. I figured there might be a reason it was returning an array. Anyhow, no biggie on this end. Nothing a couple findIndex(es) couldn't solve.
