### ISSUE TITLE
How to get a tonal palette

### ISSUE THREAD

**Issue by etokheim** [material-foundation/material-color-utilities#90]
Hi! Awesome project – and thanks for making it public :)

I must say that I find it very confusing to work with though. There's not a lot of examples or documentation, so I'm probably missing something...

I want to generate a Tonal palette. From the readme:

```md
Tonal palette — range of colors that varies only in tone
```

So when I actually generate a tonal palette, I would expect to get an array of colors, with color values for each step (0, 10, 20, ... 99 and 100) – like from other Material Design color utilities, ie. the Figma Plugin or m3 theme builder.

But as you can see, the `TonalPalette` just returns an object with a hue, chroma and cache keys?:
```js
import { TonalPalette } from "@material/material-color-utilities";
console.log(TonalPalette.fromInt( argbFromHex("#aaaaaa") ))
```

Returns:
```js
TonalPalette {
  hue: 209.49320471345078,
  chroma: 2.2472416695890782,
  cache: Map(0) {}
}
```

Is there any way to get my array of colors?
<img width="1073" alt="Screenshot 2023-03-16 at 20 42 34" src="https://user-images.githubusercontent.com/23167168/225735088-9b803e9a-ff14-461f-acc3-17a87686aab1.png">

**Comment by kirill-grouchnikov** [comment]
https://github.com/material-foundation/material-color-utilities/blob/main/typescript/palettes/tonal_palette.ts#L51

**Comment by etokheim** [comment]
> https://github.com/material-foundation/material-color-utilities/blob/main/typescript/palettes/tonal_palette.ts#L51

Not quite sure what you meant to say, but that's the function I used, yes.

**Comment by etokheim** [comment]
> https://github.com/material-foundation/material-color-utilities/blob/main/typescript/palettes/tonal_palette.ts#L51

Ah, I see, you can use the `tone` function with a supplied tone (0-100) to generate an argb value. Thanks, @kirill-grouchnikov!
