### ISSUE TITLE
the result is not match: https://m3.material.io/styles/color/the-color-system/tokens#7fd4440e-986d-443f-8b3a-4933bff16646

### ISSUE THREAD

**Issue by cieldon32** [material-foundation/material-color-utilities#96]
{
    "primary": 4285348823,
    "onPrimary": 4294967295,
    "primaryContainer": 4293516799,
    "onPrimaryContainer": 4280483932,
    "secondary": 4284636016,
    "onSecondary": 4294967295,
    "secondaryContainer": 4293451512,
    "onSecondaryContainer": 4280162603,
    "tertiary": 4286468703,
    "onTertiary": 4294967295,
    "tertiaryContainer": 4294957538,
    "onTertiaryContainer": 4281405469,
    "error": 4290386458,
    "onError": 4294967295,
    "errorContainer": 4294957782,
    "onErrorContainer": 4282449922,
    "background": 4294966271,
    "onBackground": 4280032030,
    "surface": 4294966271,
    "onSurface": 4280032030,
    "surfaceVariant": 4293386475,
    "onSurfaceVariant": 4282991950,
    "outline": 4286215551,
    "outlineVariant": 4291478735,
    "shadow": 4278190080,
    "scrim": 4278190080,
    "inverseSurface": 4281479219,
    "inverseOnSurface": 4294307828,
    "inversePrimary": 4291869951
}

there are no md.sys.color.surface-dim , ...... md.sys.color.surface-container .....

**Comment by guidezpl** [comment]
New color roles have been added recently, closing this issue
